config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  get '/artists/:id', to:'artists#show', as: 'artist'
  get 'artists', to:'artists#index', as: 'artists'
  
  
  
end

app/models/artist.rb
class Artist
    
    
  def initialize(name)
    @name = name
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
    before_action :auth 
    
    def index 
        
        if !params[:artist_name].blank?
            #requete vers l'api, recherche artiste par nom depuis formulaire
            @artists = RSpotify::Artist.search(params[:artist_name])
                if @artists.length < 1
                    flash[:notice] = "Aucun artiste correspondant"
                end
            
        end
        
    end
    
    
    def show
        #affiche le résultat de la recherche 
        @artist = RSpotify::Artist.find(params[:id]) 
        @albums = @artist.albums
    end
    
    #authification app 
    def auth
      RSpotify.authenticate(ENV['SPOTIFY_CLIENT_ID'], ENV['SPOTIFY_SECRET'])
    end

   
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/artists/_artist.html.erb
<div class="col-xs-12 text-white">
    <div class="row">
        <div class="col-xs-3">
           <%= image_tag(@image["url"]) %> 
        </div>
        <div class="col-xs-3">
           <%= artist.name %>  
        </div>
        <div class="col-xs-3">
            <%= artist.genres[0, artist.genres.length] %> 
        </div>
        <div class="col-xs-3">
            <%= link_to "Show", artist_path(artist.id) %>
        </div>
    </div>
</div>

app/views/artists/index.html.erb
<div class="container-fluid  home-page pt-1">
    <%= render 'layouts/search_bar' %>
    <div class="row d-flex">
        <div class="col search-results-container align-self-center">
            <% if @artists.nil? %>
            <p class="text-white text-center display-1">Désolé aucun artiste ne correspond à votre recherche</p>
            <% else %>
                <% if @artists.length < 1 %>
                 <p class="text-white text-center display-1">Désolé aucun artiste ne correspond à votre recherche</p>
                <% end %>
                <ul class="list-group d-flex custom-list-group">
                <% @artists.each do |artist| %>
                <% @image = artist.images.first%>
                <% if !@image.nil? %>
                    <li class="list-group-item   custom-list-item">
                        <div class="col-md-12 text-white ">
                            <div class="row">
                                <div class="col-md-4 d-flex align-self-center justify-content-center">
                                    <%= image_tag((@image["url"]), class:"thumbnail rounded-image") %> 
                                </div>
                                <div class="col-md-4 d-flex align-self-center align-content-center justify-content-center">
                                    <%= artist.name %>  
                                </div>
                                
                                <div class="col-md-4 d-flex align-self-center justify-content-center">
                                    <%= link_to "Voir", artist_path(artist.id), class:"btn btn-danger " %>
                                </div>
                            </div>
                        </div>
                    </li>
                <%# else %>
                    <!--li class="list-group-item custom-list-item"><%#= artist.name %>  <#%= link_to "Show", artist_path(artist.id) %></li-->
                <% end %>
                
                
                <% end %>
            </ul>
            <% end %>
        </div>
    </div>
</div>

app/views/artists/show.html.erb
<div class="container-fluid pt-1 text-center artist-page text-white">
    <div class="row">
        <div class="col">
            <h1><%= @artist.name %></h1>
        </div>
    </div>
    <div class="row d-flex mt-5 justify-content-center">
        <% @albums.each do |album| %>
            <% @image = album.images.first %>
            <% if !@image.nil? %>
        <div class="col-md-2 p-0  mx-5 mb-5  album-container d-flex position-relative ">
            <%= image_tag((@image["url"]), class:"album-image thumbnail-lg") %> 
            <div class="overlay ">
                <p class="album-name  mt-5"><%= album.name %></p>
                <p class="album-date "><%= album.release_date  %></p>
            </div>
        </div>
       
        <%end%>
<% end %>   
    </div>
</div>


 

app/views/home/index.html.erb
<div class="container-fluid home-page pt-5">
    <div class="row h-50 d-flex pt-5">
        <div class="col-md-12 py-5 mt-5  align-self-end text-center tagline-container text-white">
            <h1 class="mb-4">Vos artistes favoris à portée de clic</h1>
            <p>Entez le nom d'un artiste et découvrez sa discographie</p>
            <%= render 'layouts/search_bar' %>
        </div>
    </div>
    
</div>

app/views/layouts/_search_bar.html.erb
<div class="row mb-5">
        <div class="col-md-8 offset-md-2 search-container">
       
         <%= form_tag(artists_path, :method => "get", id: "search-form", class:"input-group search-bar p-1") do %>
          <%= text_field_tag :artist_name, "", placeholder: "Un artiste en tête? ", class:"text-white form-control search-input", id:"search-bar", required: true%>
          <span class="input-group-btn">
          <%= button_tag(type: "submit", class: "btn search-btn btn-sm" ) do %>
           <i class="material-icons">
            search
           </i>
          <% end %>
          </span>
          <% end %>
        </div>
    </div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spotifinder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>

<%= yield %>

</body>
</html>